#pragma once

// used in CStreaming
const uint32 TOTAL_DFF_MODEL_IDS = 20000;
const uint32 TOTAL_TXD_MODEL_IDS = 5000;
const uint32 TOTAL_COL_MODEL_IDS = 255;
const uint32 TOTAL_IPL_MODEL_IDS = 256;
const uint32 TOTAL_DAT_MODEL_IDS = 64;
const uint32 TOTAL_IFP_MODEL_IDS = 180;
const uint32 TOTAL_RRR_MODEL_IDS = 475;
const uint32 TOTAL_SCM_MODEL_IDS = 82;
const uint32 TOTAL_INTERNAL_MODEL_IDS = 4; // internal use?

const uint32 TOTAL_IMG_ARCHIVES = 8;
const uint32 TOTAL_LOADED_PEDS = 8;
const uint32 TOTAL_GANGS = 10;

const uint32 TOTAL_SCRIPTED_TASKS = 128;
const uint32 TOTAL_SCRIPTED_BRAIN_TASK_ENTRIES = 48;
const int32  TOTAL_DECISION_MAKERS = 20;
const int32  TOTAL_PED_GROUPS = 8;

// used in CRenderer
const int32 TOTAL_ENTITY_SCAN_LISTS = 5;
const float MAX_LOD_DISTANCE = 300.0f;
const float MAX_LOWLOD_DISTANCE = 150.0f;
const float MAX_FADING_DISTANCE = 20.0f;
const float MAX_STREAMING_DISTANCE = 50.0f;
const float MAX_INVISIBLE_ENTITY_DISTANCE = 30.0f;
const float MAX_INVISIBLE_VEHICLE_DISTANCE = 200.0f;
const float MAX_STREAMING_RADIUS = 10000.0f;
const float STREAMING_ANGLE_THRESHOLD = 20.62648f;
const float MAX_BIGBUILDING_STREAMING_RADIUS = 80000.0f;
const float BIGBUILDING_STREAMING_ANGLE_THRESHOLD = 40.107f;
const float LOWLOD_CAMERA_HEIGHT_THRESHOLD = 80.0f;
