#pragma once

enum eCarDrivingStyle : int8
{
    DRIVING_STYLE_STOP_FOR_CARS,
    DRIVING_STYLE_SLOW_DOWN_FOR_CARS,
    DRIVING_STYLE_AVOID_CARS,
    DRIVING_STYLE_PLOUGH_THROUGH,
    DRIVING_STYLE_STOP_FOR_CARS_IGNORE_LIGHTS
};