/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eClothesTexturePart
{
  CLOTHES_TEXTURE_TORSO = 0x0,
  CLOTHES_TEXTURE_HEAD = 0x1,
  CLOTHES_TEXTURE_LEGS = 0x2,
  CLOTHES_TEXTURE_SHOES = 0x3,
  CLOTHES_TEXTURE_LOWER_LEFT_ARM = 0x4,
  CLOTHES_TEXTURE_UPPER_LEFT_ARM = 0x5,
  CLOTHES_TEXTURE_UPPER_RIGHT_ARM = 0x6,
  CLOTHES_TEXTURE_LOWER_RIGHT_ARM = 0x7,
  CLOTHES_TEXTURE_BACK_TOP = 0x8,
  CLOTHES_TEXTURE_LEFT_CHEST = 0x9,
  CLOTHES_TEXTURE_RIGHT_CHEST = 0xA,
  CLOTHES_TEXTURE_STOMACH = 0xB,
  CLOTHES_TEXTURE_LOWER_BACK = 0xB,
  CLOTHES_TEXTURE_NECKLACE = 0xD,
  CLOTHES_TEXTURE_BRACELET = 0xE,
  CLOTHES_TEXTURE_GLASSES = 0xF,
  CLOTHES_TEXTURE_HATS = 0x10,
  CLOTHES_TEXTURE_SPECIAL = 0x11,
  CLOTHES_TEXTURE_UNAVAILABLE = 0x12,
};