/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eEmergencyPedVoices : unsigned int {
	VOICE_EMG_ARMY1,
	VOICE_EMG_ARMY2,
	VOICE_EMG_ARMY3,
	VOICE_EMG_EMT1,
	VOICE_EMG_EMT2,
	VOICE_EMG_EMT3,
	VOICE_EMG_EMT4,
	VOICE_EMG_EMT5,
	VOICE_EMG_FBI2,
	VOICE_EMG_FBI3,
	VOICE_EMG_FBI4,
	VOICE_EMG_FBI5,
	VOICE_EMG_FBI6,
	VOICE_EMG_LAPD1,
	VOICE_EMG_LAPD2,
	VOICE_EMG_LAPD3,
	VOICE_EMG_LAPD4,
	VOICE_EMG_LAPD5,
	VOICE_EMG_LAPD6,
	VOICE_EMG_LAPD7,
	VOICE_EMG_LAPD8,
	VOICE_EMG_LVPD1,
	VOICE_EMG_LVPD2,
	VOICE_EMG_LVPD3,
	VOICE_EMG_LVPD4,
	VOICE_EMG_LVPD5,
	VOICE_EMG_MCOP1,
	VOICE_EMG_MCOP2,
	VOICE_EMG_MCOP3,
	VOICE_EMG_MCOP4,
	VOICE_EMG_MCOP5,
	VOICE_EMG_MCOP6,
	VOICE_EMG_PULASKI,
	VOICE_EMG_RCOP1,
	VOICE_EMG_RCOP2,
	VOICE_EMG_RCOP3,
	VOICE_EMG_RCOP4,
	VOICE_EMG_SFPD1,
	VOICE_EMG_SFPD2,
	VOICE_EMG_SFPD3,
	VOICE_EMG_SFPD4,
	VOICE_EMG_SFPD5,
	VOICE_EMG_SWAT1,
	VOICE_EMG_SWAT2,
	VOICE_EMG_SWAT4,
	VOICE_EMG_SWAT6
};
