#pragma once

enum eMeleeCombo : uint8 {
    MELEE_COMBO_IDLE = 0x0,
    MELEE_COMBO_MOVE = 0x1,
    MELEE_COMBO_BLOCK = 0x2,
    MELEE_COMBO_END = 0x3,
    MELEE_COMBO_UNARMED_1 = 0x4,
    MELEE_COMBO_UNARMED_2 = 0x5,
    MELEE_COMBO_UNARMED_3 = 0x6,
    MELEE_COMBO_UNARMED_4 = 0x7,
    MELEE_COMBO_BBALLBAT = 0x8,
    MELEE_COMBO_KNIFE = 0x9,
    MELEE_COMBO_GOLFCLUB = 0xA,
    MELEE_COMBO_SWORD = 0xB,
    MELEE_COMBO_CHAINSAW = 0xC,
    MELEE_COMBO_DILDO = 0xD,
    MELEE_COMBO_FLOWERS = 0xE,
    MELEE_COMBO_KICK_STD = 0xF,
    MELEE_COMBO_PISTOL_WHIP = 0x10,
    MELEE_COMBO_NUM = 0x11,
};
