#pragma once

#include "CommandParser/Parser.hpp"

/*
* Unused commands
*/

void NoOp() {}

REGISTER_COMMAND_HANDLER(COMMAND_CASE, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_BREAK, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_SWITCH, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_DEFAULT, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_ENDSWITCH, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_CONST_INT, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_CONST_FLOAT, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_GET_GROUP_LEADER, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_DRAW_RECT_WITH_TITLE, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_SET_ATTRACTOR_RADIUS, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_CLEAR_ALL_BREAKPOINTS, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_CLEAR_ALL_WATCHPOINTS, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_IS_THIS_MODEL_A_TRAIN, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_SET_TIME_ONE_DAY_BACK, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_GET_CLOSEST_ATTRACTOR, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_GET_VEHICLE_DIRT_LEVEL, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_TASK_SIT_IN_RESTAURANT, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_SET_WATER_CONFIGURATION, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_CLEAR_ALL_VIEW_VARIABLES, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_GET_OBJECT_ANIM_TOTAL_TIME, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_TASK_USE_NEARBY_ENTRY_EXIT, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_TASK_USE_ATTRACTOR_ADVANCED, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_SET_OBJECT_ANIM_PLAYING_FLAG, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_GET_MODEL_NAME_FOR_DEBUG_ONLY, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_GET_VEHICLE_CHAR_IS_STANDING_ON, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_ADD_INTERESTING_ENTITY_FOR_CHAR, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_CLEAR_INTERESTING_ENTITIES_FOR_CHAR, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_TASK_FOLLOW_PATH_NODES_TO_COORD_SHOOTING, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_START_PLAYBACK_RECORDED_CAR_USING_AI_LOOPED, NoOp);
REGISTER_COMMAND_HANDLER(COMMAND_GET_RANDOM_ATTRACTOR_ON_CLOSEST_OBJECT_OF_TYPE, NoOp);
