#pragma once

enum eSFX {
    // slot 28
    SFX_WEAPON_BULLET_SWISH_1     = 0,
    SFX_WEAPON_BULLET_SWISH_2     = 1,
    SFX_WEAPON_BULLET_SWISH_3     = 2,
    // slot 59
    SFX_FRONTEND_SCANNER_NOISE_START = 3,
    SFX_FRONTEND_TIMER_COUNT_LEFT    = 4,
    SFX_FRONTEND_TIMER_COUNT_RIGHT   = 5,
    SFX_FRONTEND_WAKEUP_AMPLIFIER    = 8,
    SFX_FRONTEND_BUY_CAR_MOD         = 9,
    SFX_FRONTEND_DISPLAY_INFO_LEFT   = 14, //
    SFX_FRONTEND_DISPLAY_INFO_RIGHT  = 15, // ?
    SFX_FRONTEND_PICKUP_MONEY_LEFT   = 16,
    SFX_FRONTEND_PICKUP_MONEY_RIGHT  = 17,
    SFX_FRONTEND_RADIO_CLICK         = 23,
    SFX_FRONTEND_SCANNER_CLICK       = 24,
    SFX_FRONTEND_START_LEFT          = 25, // ?
    SFX_FRONTEND_START_RIGHT         = 26, // ?
    SFX_FRONTEND_PICKUP_WEAPON_LEFT  = 27,
    SFX_FRONTEND_PICKUP_WEAPON_RIGHT = 28,
    // slot 60
    SFX_FRONTEND_BACK_LEFT           = 0,  // manhunt
    SFX_FRONTEND_BACK_RIGHT          = 1,  // manhunt
    SFX_FRONTEND_ERROR_LEFT          = 2,  //
    SFX_FRONTEND_ERROR_RIGHT         = 3,  //
    SFX_FRONTEND_HIGHLIGHT_LEFT      = 4,  // gta3
    SFX_FRONTEND_HIGHLIGHT_RIGHT     = 5,  // gta3
    SFX_FRONTEND_SELECT_LEFT         = 6,  // manhunt
    SFX_FRONTEND_SELECT_RIGHT        = 7,  // manhunt
    SFX_FRONTEND_NOISE_TEST          = 8,  //
};
